---
# tasks file for moodle

- name: Check if Moodle archive exists
  stat: path=/tmp/moodle-3.3.4.tgz
  register: moodle_path

- name: Download Moodle archive
  get_url: dest=/tmp/ url=https://download.moodle.org/download.php/direct/stable33/moodle-3.3.4.tgz
  when: (moodle_path.stat.exists == false)

- name: Extract moodle
  unarchive:
    src: /tmp/moodle-3.3.4.tgz 
    dest: /tmp
    owner: www-data
    group: www-data
    copy: no
  become: yes

- name: Move Moodle install files
  command: mv /tmp/moodle /var/www/html/{{hostname}}
  become: yes


- name: Fix ownership of Moodle
  file: path=/srv/moodle owner=nginx group=nginx state=directory recurse=yes

- name: Create moodledata directory
  file: path=/srv/moodle/moodledata owner=nginx group=nginx state=directory recurse=yes

