--- 
- 
  name: "Check if Moodle archive exists"
  register: moodle_path
  stat: path=/tmp/moodle-3.3.4.tgz
- 
  get_url: "dest=/tmp/ url=https://download.moodle.org/download.php/direct/stable33/moodle-3.3.4.tgz"
  name: "Download Moodle archive"
  when: "(moodle_path.stat.exists == false)"
- 
  become: true
  name: "Extract moodle"
  unarchive: 
    copy: false
    dest: /tmp
    group: www-data
    owner: www-data
    src: /tmp/moodle-3.3.4.tgz
- 
  become: true
  command: "mv /tmp/moodle /var/www/html/{{hostname}}"
  name: "Move moodle install files"
- 
  file: "path=/srv/moodle owner=azureadmin group=azureadmin state=directory recurse=yes"
  name: "Fix ownership of Moodle"
- 
  file: "path=/srv/moodle/moodledata owner=azureadmin group=azureadmin state=directory recurse=yes"
  name: "Create moodledata directory"
