
# tasks file for moodle

- name: Create webroot
  file:
    state: directory
    path: /var/www/html
    owner: root
    group: root
    mode: 0755
  become: yes
  
- name: Download Moodle archive
  get_url: dest=/tmp/ url=https://download.moodle.org/download.php/direct/stable33/moodle-3.3.4.tgz
  when: (moodle_path.stat.exists == false)

- name: Extract moodle
  unarchive:
    src: /tmp/ url=https://download.moodle.org/download.php/direct/stable33/moodle-3.3.4.tgz
    dest: /tmp
    owner: www-data
    group: www-data
    copy: no
  become: yes


- name: Move Moodle install files
  command: mv /tmp/moodle /var/www/html/{{hostname}}
  become: yes


- name: Fix ownership of Moodle
  file: path=/srv/moodle owner=azureadmin group=azureadmin state=directory recurse=yes

- name: Create moodledata directory
  file: path=/srv/moodle/moodledata owner=azureadmin group=azureadmin state=directory recurse=yes
